### ISSUE TITLE
Allocations notes

### ISSUE THREAD

**Issue by chadoh** [AutarkLabs/open-enterprise#1317]
From @jayalaves, 9 Oct:

- [x] _fixed by #1311:_ Permission descriptions are outdated, it’s Budget account, not allocations account
- [ ] _in progress #1318:_ Editing a budget doesn’t work. Once the option is clicked, all the information on screen disappears and I have to reload the app
- [x] _fixed by #1313:_ Budget cards shouldn’t be clickable at this stage, since doing so doesn’t lead to anything
- [x] Inserting any number larger than 300000 for Amount in New Budget triggers the error “Amount must be smaller than underlying funds”, even though slightly smaller amounts are accepted and the funds are still not there
- [x] _fixed by #1313:_ There are three budget cards per row, while there should be four
- [x] _fixed by #1313:_ Change spacing between cards to 16px, not 32px
- [ ] Submitting new budgets with large amounts don’t output any feedback to the user
- [ ] Input titles aren’t the right styling (change to Overpass Regular 12 `#637381`)
- [ ] Green stroke for a correct address doesn’t sit well on top of the existing stroke
- [ ] Can’t scroll in Allocations to view Allocations History, need to zoom out
- [ ] Progress bar inside Budget cards needs to be full width with 24px spacing with the left and right borders
- [ ] Clicking outside of a side panel should have the smooth animation as when the side panel is introduced
- [ ] Zooming in on the app with the touchpad and then zooming out, everything becomes senseless to clicks
- [ ] Can’t test what the next events within this app are because Dot Voting doesn’t load

**Comment by topocount** [comment]
Hey @chadoh We just noticed this change, probably when switching from 3 cards in a row to 4 where the space between the table and the cards is gone: 
![Screenshot from 2019-10-11 09-57-20](https://user-images.githubusercontent.com/17910833/66617103-967d4480-ec0e-11e9-82be-eb3e85c7b780.png)

**Comment by chadoh** [comment]
Kevin: yes, looks like I missed that. Margin-bottom on the list of budgets should be all it needs.

**Comment by javieralaves** [comment]
Some parts of this issue are obsolete by now or being addressed by other tickets that are already part of epics in the product management board, so I'll be closing this for now.
